# Generated by Django 3.0.7 on 2020-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20200713_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date_time',
            field=models.DateTimeField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
