# Generated by Django 3.0.7 on 2020-07-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_host_user'),
        ('basic', '0005_auto_20200708_1853'),
    ]

    operations = [
    ]
