# Generated by Django 3.0.7 on 2020-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_merge_20200722_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='blank', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_image',
            field=models.ImageField(blank=True, default='download.jpeg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
