# Generated by Django 3.0.7 on 2020-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20200722_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='flat_no',
            field=models.IntegerField(default=0),
        ),
    ]
